# https://redocly.com/docs/cli/rules/built-in-rules/
# rules based on recommend ruleset of redocly (https://redocly.com/docs/cli/rules/recommended/)
# comments show the default value in the recommended ruleset, if not specified the rule was turned off
rules:
  # special rules
  no-unresolved-refs: error
  no-unused-components: warn
  security-defined: error
  spec: error
  spec-components-invalid-map-name: error
  spec-strict-refs: error  #

  # info
  info-contact: error  #
  info-license: error  # warn
  info-license-url: error  # warn

  # operations
  operation-2xx-response: warn
  operation-4xx-response: warn
  operation-4xx-problem-details-rfc7807: error  #
  operation-description: warn  # <--
  operation-operationId: off  # warn
  operation-operationId-unique: error
  operation-operationId-url-safe: error
  operation-summary: error

  # parameters
  boolean-parameter-prefixes: off
  no-invalid-parameter-examples: error  #
  operation-parameters-unique: error
  parameter-description: warn  # <--
  path-declaration-must-exist: error
  path-not-include-query: error
  path-parameters-defined: error

  # paths
  no-ambiguous-paths: warn  #
  no-http-verbs-in-paths: error  #
  no-identical-paths: error
  no-path-trailing-slash: error
  path-excludes-patterns: off
  path-segment-plural:
    severity: error
    ignoreLastPathSegment: true
    exceptions:
      - iso20022
      - status
  paths-kebab-case: error  #

  # Requests, Responses, and Schemas
  no-enum-type-mismatch: error
  no-example-value-and-externalValue: error
  no-invalid-media-type-examples: error  #
  no-invalid-schema-examples: error  #
  request-mime-type:
    severity: warn
    allowedValues:
      - application/json
      - application/xml
  response-mime-type:
    severity: warn
    allowedValues:
      - application/json
      - application/problem+json
      - application/xml
  response-contains-header: off  #
  response-contains-property: off
  scalar-property-missing-example: error
  required-string-property-missing-min-length: off

  # servers
  no-empty-servers: error
  no-server-example.com: warn
  no-server-trailing-slash: error
  no-server-variables-empty-enum: error
  no-undefined-server-variable: error

  # tags
  operation-singular-tag: error  #
  operation-tag-defined: error  #
  tag-description: warn
  tags-alphabetical: error  #
