name: "Lint SFTI Specifications: openapi compliance"

on:
  workflow_call:
    inputs:
      filenames:
        type: string
        default: '*.yaml'
        description: 'Files to be linted. (default: *.yaml, list of files sperated by whitespace)'

env:
  REDOCLY_VERSION: '1.9.1'

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      LINT: ${{ steps.check.outputs.LINT }}
    steps:
      - name: Checkout Lint Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }} # checkout last commit of PR instead of merge commit

      - name: get commit message
        id: check
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B | tr -d '\n')
          if [[ $COMMIT_MESSAGE = *'[skip-workflow]'* ]]; then
            lint=false
          else
            lint=true
          fi
          echo "LINT=$lint" >> $GITHUB_OUTPUT

  lint-openapi-detailed:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.LINT

    steps:
      - name: Checkout Lint Repo
        uses: actions/checkout@v4

      - name: Checkout Config Repo
        uses: actions/checkout@v4
        with:
          repository: swissfintechinnovations/.github
          path: .github
          ref: dev/redocly-lint-workflow # TODO remove before merge

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install redocly $REDOCLY_VERSION
        run: |
          npm install -g @redocly/cli@$REDOCLY_VERSION

      - name: Lint SFTI Specifications (detailed)
        id: lint
        run: |
          for file in ${{ inputs.filenames }}; do
            echo "*** $file ***"
            name=$(b=${file##*/}; echo ${file%.*})
            # npx @redocly/cli@$REDOCLY_VERSION lint --config=.github/.github/redocly.yaml $file > lint_$name.log
            npx @redocly/cli@$REDOCLY_VERSION lint --config=.github/.github/redocly.yaml $file
          done
        continue-on-error: true

  lint-openapi:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.LINT

    steps:
      - name: Checkout Lint Repo
        uses: actions/checkout@v4

      - name: Checkout Config Repo
        uses: actions/checkout@v4
        with:
          repository: swissfintechinnovations/.github
          path: .github
          ref: dev/redocly-lint-workflow # TODO remove before merge

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install redocly $REDOCLY_VERSION
        run: |
          npm install -g @redocly/cli@$REDOCLY_VERSION

      - name: Lint SFTI Specifications
        if: always()
        run: |
          npx @redocly/cli@$REDOCLY_VERSION lint --config=.github/.github/redocly.yaml --format=stylish ${{ inputs.filenames }}

      - name: Lint SFTI Specifications report overview
        if: always()
        run: |
          echo ""
          echo "---------------------------: Summary :----------------------------"
          npx @redocly/cli@$REDOCLY_VERSION lint --config=.github/.github/redocly.yaml --format=summary ${{ inputs.filenames }}