name: Yaml lint workflow
# description: Check specifications for SFTI's yaml style guides.

on:
    workflow_call:
        inputs:
            filenames:
                type: string
                required: true
                description: "Files to be linted. (default: *.yaml, list of files separated by whitespace)"

jobs:
    lint-yaml:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Lint Repo
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref || github.ref }}

            - name: Checkout Config Repo
              uses: actions/checkout@v4
              with:
                  repository: swissfintechinnovations/.github
                  path: github

            - name: Get commit message
              id: skip
              run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=%B | tr -d '\n')" >> $GITHUB_OUTPUT # set last commit message as env file (since env var will be not supported)

            - name: Lint yaml APIs
              if: ${{ !contains(steps.skip.outputs.COMMIT_MESSAGE, '[skip-workflow]') }} # check commit message via env var - skip step if [skip-workflow] is set
              run: yamllint -c github/.github/.yamllint -f github ${{ inputs.filenames }}
