name: Update copyright year in license file (reusable)

on:
  workflow_call:

jobs:
  update-license-year:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Action Update License Year
        uses: FantasticFiasco/action-update-license-year@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: LICENSE

      - name: Merge pull request
        run: |
          gh pr merge --admin --merge --delete-branch --body "Automated license year update"
        env:
          GITHUB_TOKEN: ${{ secrets.SFTI_BOT_TOKEN }}

