name: Bundle status workflow
# description: Check exit status of last bundle workflow run.

on:
  workflow_call:
    inputs:
      bundle_status:
          type: string
          required: true
          description: "Exit status of last bundle workflow run. Possible values: success, failure, canceled."

jobs:
  bundle-run-status:
      runs-on: ubuntu-latest
      steps:
        - name: Bundle action status
          run: |
            if [[ ${{ inputs.bundle_status }} == 'success' ]]; then
              echo "Bundle workflow successful (${{ github.event.workflow_run.html_url }})."
            elif [[ ${{ inputs.bundle_status }} == 'failure' ]]; then
              echo "::error::Bundle workflow failed!"
              echo "See details: ${{ github.event.workflow_run.html_url }}"
              exit 1
            else
              echo "::warning::Some unexpected behavior of the bundle workflow detected."
              echo "See details: ${{ github.event.workflow_run.html_url }}"
            fi